"use client";

import { useEffect, useState } from "react";
import { Phone, Sparkles, RefreshCw } from "lucide-react";
import { C } from "@/lib/design";

const gold = "var(--brand, #c9a83a)";

type Props = {
  leadId: string;
  initialPoints: string[] | null;
  initialGeneratedAt: string | null;
};

/**
 * Pre-Call Brief — three operational talking points generated by AI, shown
 * at the top of the lead detail page (above the tabs). Auto-generates on
 * first view if not cached; the seller can click Refresh to re-run after
 * enrichment data changes. Separate from <AISummary> because this is the
 * "what to say in the next 30 seconds" view, not the research blurb.
 */
export default function PreCallBrief({ leadId, initialPoints, initialGeneratedAt }: Props) {
  const [points, setPoints] = useState<string[] | null>(initialPoints);
  const [generatedAt, setGeneratedAt] = useState<string | null>(initialGeneratedAt);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Lazy auto-generate: if the lead has never had a brief built, kick off
  // generation as soon as the seller opens the page. No spinner gate on the
  // first paint — the rest of the page renders normally, the card just
  // flips from "Generating…" to filled in-place once the AI returns.
  useEffect(() => {
    if (!points && !loading) {
      void generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/leads/${leadId}/talking-points`, { method: "POST" });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body?.error ?? `HTTP ${res.status}`);
      setPoints(body.points ?? null);
      setGeneratedAt(new Date().toISOString());
    } catch (e: any) {
      setError(e?.message ?? "Generation failed");
    } finally {
      setLoading(false);
    }
  }

  const stamp = generatedAt
    ? new Date(generatedAt).toLocaleString("en-GB", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })
    : null;

  return (
    <div className="rounded-2xl border p-5 mb-6"
      style={{
        background: "linear-gradient(135deg, color-mix(in srgb, var(--brand, #c9a83a) 5%, var(--card)), var(--card))",
        borderColor: "color-mix(in srgb, var(--brand, #c9a83a) 25%, var(--border))",
        boxShadow: "0 4px 20px rgba(0,0,0,0.04)",
      }}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="rounded-lg flex items-center justify-center" style={{ width: 28, height: 28, backgroundColor: gold }}>
            <Phone size={14} style={{ color: "#fff" }} />
          </div>
          <div>
            <p className="text-sm font-bold uppercase tracking-wider" style={{ color: C.textPrimary, letterSpacing: "0.08em" }}>
              Pre-Call Brief
            </p>
            <p className="text-[10px]" style={{ color: C.textMuted }}>
              {loading ? "Generating talking points…" : stamp ? `Generated ${stamp}` : "AI-generated talking points"}
            </p>
          </div>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className="inline-flex items-center gap-1.5 text-[10px] font-semibold px-2.5 py-1 rounded-md transition-opacity hover:opacity-80 disabled:opacity-50"
          style={{ backgroundColor: C.surface, color: C.textBody, border: `1px solid ${C.border}` }}
        >
          <RefreshCw size={11} className={loading ? "animate-spin" : ""} />
          {points ? "Refresh" : "Generate"}
        </button>
      </div>

      {error && (
        <p className="text-xs mb-2" style={{ color: "#B91C1C" }}>{error}</p>
      )}

      {points && points.length > 0 ? (
        <ol className="space-y-2">
          {points.map((p, i) => (
            <li key={i} className="flex gap-3">
              <span
                className="flex items-center justify-center rounded-full shrink-0 text-[10px] font-bold"
                style={{ width: 20, height: 20, backgroundColor: gold, color: "#fff", marginTop: 1 }}
              >
                {i + 1}
              </span>
              <p className="text-sm leading-snug" style={{ color: C.textPrimary }}>{p}</p>
            </li>
          ))}
        </ol>
      ) : loading ? (
        <div className="space-y-2">
          {[1, 2, 3].map((i) => (
            <div key={i} className="flex gap-3 animate-pulse">
              <div className="rounded-full shrink-0" style={{ width: 20, height: 20, backgroundColor: C.border }} />
              <div className="flex-1 h-4 rounded" style={{ backgroundColor: C.border }} />
            </div>
          ))}
        </div>
      ) : (
        <p className="text-sm flex items-center gap-2" style={{ color: C.textMuted }}>
          <Sparkles size={12} /> Click Generate to build a 30-second pre-call brief from this lead&apos;s enrichment data.
        </p>
      )}
    </div>
  );
}
