"use client";

import { useEffect, useRef, useState } from "react";
import { Sparkles, RefreshCw, Target, Compass, Quote, ClipboardList, ChevronDown, UserRound, Lightbulb, ShieldAlert, Building2, Brain } from "lucide-react";
import { C } from "@/lib/design";
import LogoLoader from "@/components/LogoLoader";

const gold = "var(--brand, #c9a83a)";

// Pre-Call Brief — three structured prompts (pain / fit / opener) generated by
// AI from the lead's enrichment + ICP.
//
// Two modes share one entry point:
//  1. PREMIUM (lead detail) — pass `leadId`. Full card with accent bars, icon
//     discs and a quoted opener. ALWAYS rendered, auto-generates on first view
//     when no brief is cached, with a Refresh button. (Fran 2026-06-05: the
//     brief must always be visible AND keep the pretty cards.)
//  2. COMPACT (the /queue pending-call rows) — pass only `talkingPoints`. A
//     collapsed toggle that expands inline, so it never overlaps neighbouring
//     rows. No auto-generation (we don't fire N AI calls when the queue opens).

type PointType = "snapshot" | "account" | "read" | "pain" | "fit" | "hook" | "opener" | "objection";
type TalkingPoint = { type: PointType; text: string };
type AnyPoint = TalkingPoint | string;

const ORDER: PointType[] = ["snapshot", "account", "read", "pain", "fit", "hook", "opener", "objection"];

function isStructured(p: AnyPoint): p is TalkingPoint {
  return typeof p === "object" && p !== null && "type" in p && "text" in p && p.type in POINT_META;
}

// Order structured points canonically (snapshot → … → objection); legacy
// strings / unknown types keep their original position at the end.
function orderPoints(points: AnyPoint[]): AnyPoint[] {
  const rank = (p: AnyPoint) => (isStructured(p) ? ORDER.indexOf(p.type) : 99);
  return points.map((p, i) => ({ p, i })).sort((a, b) => rank(a.p) - rank(b.p) || a.i - b.i).map((x) => x.p);
}

// Per-type visual language. Pain reads as urgency-red, fit as trust-blue,
// opener as conversation-amber — distinct from the global brand gold.
const POINT_META: Record<PointType, {
  label: string;
  icon: typeof Target;
  accent: string;
  tint: string;
  pillBg: string;
  pillFg: string;
}> = {
  snapshot: {
    label: "Snapshot",
    icon: UserRound,
    accent: "#64748B",
    tint: "linear-gradient(135deg, rgba(248,250,252,0.95) 0%, rgba(255,255,255,0.6) 70%)",
    pillBg: "#E2E8F0",
    pillFg: "#334155",
  },
  account: {
    label: "Account angle",
    icon: Building2,
    accent: "#0891B2",
    tint: "linear-gradient(135deg, rgba(236,254,255,0.95) 0%, rgba(255,255,255,0.6) 70%)",
    pillBg: "#CFFAFE",
    pillFg: "#155E75",
  },
  read: {
    label: "How to read them",
    icon: Brain,
    accent: "#DB2777",
    tint: "linear-gradient(135deg, rgba(253,242,248,0.95) 0%, rgba(255,255,255,0.6) 70%)",
    pillBg: "#FCE7F3",
    pillFg: "#9D174D",
  },
  pain: {
    label: "Pain",
    icon: Target,
    accent: "#DC2626",
    tint: "linear-gradient(135deg, rgba(254,242,242,0.95) 0%, rgba(255,255,255,0.6) 70%)",
    pillBg: "#FEE2E2",
    pillFg: "#991B1B",
  },
  fit: {
    label: "Why we fit",
    icon: Compass,
    accent: "#2563EB",
    tint: "linear-gradient(135deg, rgba(239,246,255,0.95) 0%, rgba(255,255,255,0.6) 70%)",
    pillBg: "#DBEAFE",
    pillFg: "#1E40AF",
  },
  hook: {
    label: "Personal hook",
    icon: Lightbulb,
    accent: "#7C3AED",
    tint: "linear-gradient(135deg, rgba(245,243,255,0.95) 0%, rgba(255,255,255,0.6) 70%)",
    pillBg: "#EDE9FE",
    pillFg: "#5B21B6",
  },
  opener: {
    label: "Opener",
    icon: Quote,
    accent: "#D97706",
    tint: "linear-gradient(135deg, rgba(255,251,235,0.95) 0%, rgba(255,255,255,0.6) 70%)",
    pillBg: "#FEF3C7",
    pillFg: "#92400E",
  },
  objection: {
    label: "Likely objection",
    icon: ShieldAlert,
    accent: "#0D9488",
    tint: "linear-gradient(135deg, rgba(240,253,250,0.95) 0%, rgba(255,255,255,0.6) 70%)",
    pillBg: "#CCFBF1",
    pillFg: "#115E59",
  },
};

// The brief reads as two groups: "the read" (who they are + how to play it) and
// "the play" (pain/fit/hook + what to say). Opener is rendered full-width at the
// end of the play group so the verbatim line stands out.
const READ_TYPES: PointType[] = ["snapshot", "account", "read"];
const PLAY_TYPES: PointType[] = ["pain", "fit", "hook", "objection"];

function GroupLabel({ children }: { children: string }) {
  return (
    <p className="text-[9.5px] font-bold uppercase tracking-wider mb-2" style={{ color: gold, letterSpacing: "0.12em" }}>
      {children}
    </p>
  );
}

function BriefCard({ p }: { p: TalkingPoint }) {
  const meta = POINT_META[p.type];
  const Icon = meta.icon;
  const isOpener = p.type === "opener";
  return (
    <div className="relative rounded-xl overflow-hidden border transition-shadow hover:shadow-sm h-full"
      style={{ background: `color-mix(in srgb, ${meta.accent} 7%, ${C.card})`, borderColor: `color-mix(in srgb, ${meta.accent} 22%, ${C.border})` }}>
      <div className="absolute left-0 top-0 bottom-0" style={{ width: 3, backgroundColor: meta.accent }} />
      <div className="flex gap-3.5 p-4 pl-5">
        <div className="rounded-full flex items-center justify-center shrink-0 shadow-sm"
          style={{ width: 34, height: 34, background: `linear-gradient(135deg, ${meta.accent}, color-mix(in srgb, ${meta.accent} 70%, white))` }}>
          <Icon size={15} style={{ color: "#fff" }} strokeWidth={2.4} />
        </div>
        <div className="flex-1 min-w-0">
          <span className="inline-flex items-center text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded-md mb-1.5"
            style={{ backgroundColor: `color-mix(in srgb, ${meta.accent} 15%, transparent)`, color: meta.accent, letterSpacing: "0.08em" }}>
            {meta.label}
          </span>
          {isOpener ? (
            <p className="text-[14px] leading-snug italic" style={{ color: C.textPrimary, fontFamily: "Georgia, 'Times New Roman', serif" }}>
              &ldquo;{p.text}&rdquo;
            </p>
          ) : (
            <p className="text-[13.5px] leading-snug" style={{ color: C.textPrimary }}>{p.text}</p>
          )}
        </div>
      </div>
    </div>
  );
}

function LegacyCard({ text, n }: { text: string; n: number }) {
  return (
    <div className="flex gap-3 rounded-xl p-4 border" style={{ backgroundColor: C.surface, borderColor: C.border }}>
      <span className="flex items-center justify-center rounded-full shrink-0 text-[11px] font-bold"
        style={{ width: 24, height: 24, backgroundColor: gold, color: "#fff" }}>{n}</span>
      <p className="text-[13.5px] leading-snug" style={{ color: C.textPrimary }}>{text}</p>
    </div>
  );
}

export default function PreCallBrief({
  leadId,
  initialPoints,
  initialGeneratedAt,
  talkingPoints,
}: {
  leadId?: string;
  initialPoints?: AnyPoint[] | null;
  initialGeneratedAt?: string | null;
  /** Static prop (QueueClient): a pre-loaded list, no auto-generation. */
  talkingPoints?: AnyPoint[] | null;
}) {
  if (leadId) {
    return <PremiumBrief leadId={leadId} initialPoints={initialPoints ?? null} initialGeneratedAt={initialGeneratedAt ?? null} />;
  }
  return <CompactBrief talkingPoints={talkingPoints ?? null} />;
}

// ── Premium card (lead detail) ────────────────────────────────────────────────
function PremiumBrief({ leadId, initialPoints, initialGeneratedAt }: {
  leadId: string;
  initialPoints: AnyPoint[] | null;
  initialGeneratedAt: string | null;
}) {
  const [points, setPoints] = useState<AnyPoint[] | null>(initialPoints);
  const [generatedAt, setGeneratedAt] = useState<string | null>(initialGeneratedAt);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const ranOnce = useRef(false);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/leads/${leadId}/talking-points`, { method: "POST" });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body?.error ?? `HTTP ${res.status}`);
      setPoints(body.points ?? null);
      setGeneratedAt(new Date().toISOString());
    } catch (e: any) {
      setError(e?.message ?? "Generation failed");
    } finally {
      setLoading(false);
    }
  }

  // Auto-fire once on first view when nothing is cached. Ref-guarded so it
  // never loops on re-render.
  useEffect(() => {
    if (ranOnce.current) return;
    if (points && points.length > 0) return;
    ranOnce.current = true;
    void generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const stamp = generatedAt
    ? new Date(generatedAt).toLocaleString("en-GB", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })
    : null;

  return (
    <div className="relative rounded-2xl overflow-hidden mb-6"
      style={{
        background: `linear-gradient(180deg, color-mix(in srgb, ${gold} 6%, var(--card)) 0%, var(--card) 40%)`,
        border: "1px solid color-mix(in srgb, var(--brand, #c9a83a) 22%, var(--border))",
        boxShadow: "0 8px 30px -8px rgba(201,168,58,0.18), 0 2px 8px rgba(0,0,0,0.04)",
      }}>
      {/* Decorative gold corner accent */}
      <div className="absolute top-0 right-0 pointer-events-none"
        style={{
          width: 180,
          height: 180,
          background: `radial-gradient(circle at top right, color-mix(in srgb, ${gold} 18%, transparent), transparent 60%)`,
        }} />

      {/* Header */}
      <div className="relative flex items-center justify-between px-6 pt-5 pb-4">
        <div className="flex items-center gap-3">
          <div className="rounded-xl flex items-center justify-center shrink-0 shadow-sm"
            style={{
              width: 42, height: 42,
              background: `linear-gradient(135deg, ${gold} 0%, color-mix(in srgb, ${gold} 65%, white) 100%)`,
              boxShadow: `0 4px 12px color-mix(in srgb, ${gold} 35%, transparent)`,
            }}>
            <Sparkles size={18} style={{ color: "#fff" }} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <p className="text-[15px] font-bold tracking-tight" style={{ color: C.textPrimary }}>
                Pre-Call Brief
              </p>
              <span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded-md"
                style={{
                  background: `linear-gradient(135deg, ${gold}, color-mix(in srgb, ${gold} 70%, white))`,
                  color: "#fff",
                  letterSpacing: "0.06em",
                }}>
                AI
              </span>
            </div>
            <p className="text-[11px] mt-0.5" style={{ color: C.textMuted }}>
              {loading ? (
                <span className="inline-flex items-center gap-1.5">
                  <Sparkles size={10} className="animate-pulse" /> Reading LinkedIn + enrichment…
                </span>
              ) : stamp ? (
                <>Generated {stamp}</>
              ) : (
                "30-second briefing from this lead's LinkedIn + enrichment"
              )}
            </p>
          </div>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className="inline-flex items-center gap-1.5 text-[11px] font-semibold px-3 py-1.5 rounded-lg transition-all hover:shadow-sm hover:-translate-y-px disabled:opacity-50 disabled:translate-y-0"
          style={{ backgroundColor: C.surface, color: C.textBody, border: `1px solid ${C.border}` }}
        >
          <RefreshCw size={11} className={loading ? "animate-spin" : ""} />
          {points && points.length > 0 ? "Refresh" : "Generate"}
        </button>
      </div>

      {/* Body */}
      <div className="relative px-6 pb-5">
        {error && (
          <p className="text-xs mb-3 px-3 py-2 rounded-md"
            style={{ color: "#991B1B", backgroundColor: "#FEF2F2", border: "1px solid #FECACA" }}>
            {error}
          </p>
        )}

        {points && points.length > 0 ? (() => {
          const ordered = orderPoints(points);
          const read = ordered.filter((p): p is TalkingPoint => isStructured(p) && READ_TYPES.includes(p.type));
          const play = ordered.filter((p): p is TalkingPoint => isStructured(p) && PLAY_TYPES.includes(p.type));
          const opener = ordered.find((p): p is TalkingPoint => isStructured(p) && p.type === "opener");
          const legacy = ordered.filter((p) => !isStructured(p)) as string[];
          // Older briefs persisted as plain strings / unknown types → simple list.
          if (read.length === 0 && play.length === 0 && !opener) {
            return <div className="grid gap-3">{legacy.map((t, i) => <LegacyCard key={i} text={String(t)} n={i + 1} />)}</div>;
          }
          return (
            <div className="space-y-4">
              {read.length > 0 && (
                <div>
                  <GroupLabel>The read — who they are &amp; how to play it</GroupLabel>
                  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 items-stretch">
                    {read.map((p, i) => <BriefCard key={i} p={p} />)}
                  </div>
                </div>
              )}
              {(play.length > 0 || opener) && (
                <div>
                  <GroupLabel>The play — pain, fit &amp; what to say</GroupLabel>
                  {play.length > 0 && (
                    <div className="grid gap-3 sm:grid-cols-2 items-stretch">
                      {play.map((p, i) => <BriefCard key={i} p={p} />)}
                    </div>
                  )}
                  {opener && <div className="mt-3"><BriefCard p={opener} /></div>}
                </div>
              )}
              {legacy.length > 0 && (
                <div className="grid gap-3">{legacy.map((t, i) => <LegacyCard key={i} text={String(t)} n={i + 1} />)}</div>
              )}
            </div>
          );
        })() : loading ? (
          <div className="rounded-xl overflow-hidden" style={{ border: `1px solid ${C.border}` }}>
            <LogoLoader size={54} minHeight="200px" />
          </div>
        ) : (
          <div className="flex items-center justify-between gap-2 py-1">
            <p className="text-sm flex items-center gap-2" style={{ color: C.textMuted }}>
              <Sparkles size={13} /> {error ? "Couldn't build the brief." : "Building this lead's pre-call brief…"}
            </p>
            <button
              type="button"
              onClick={generate}
              className="inline-flex items-center gap-1.5 text-[11px] font-semibold px-3 py-1.5 rounded-lg"
              style={{ color: gold, border: `1px solid color-mix(in srgb, ${gold} 35%, transparent)` }}
            >
              <RefreshCw size={11} /> Generate
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// ── Compact toggle (/queue rows) ──────────────────────────────────────────────
function CompactBrief({ talkingPoints }: { talkingPoints: AnyPoint[] | null }) {
  const [open, setOpen] = useState(false);
  if (!talkingPoints || talkingPoints.length === 0) return null;

  return (
    <div className="px-5 pb-3">
      <button
        onClick={() => setOpen(v => !v)}
        className="inline-flex items-center gap-1.5 text-[11px] font-semibold px-2.5 py-1.5 rounded-lg border transition-colors"
        style={{
          color: gold,
          borderColor: open ? `color-mix(in srgb, ${gold} 45%, transparent)` : C.border,
          backgroundColor: open ? `color-mix(in srgb, ${gold} 10%, transparent)` : C.card,
        }}
      >
        <ClipboardList size={12} /> Pre-call brief
        <ChevronDown size={11} style={{ transform: open ? "rotate(180deg)" : "none", transition: "transform 0.15s" }} />
      </button>

      {open && (
        <div className="mt-2 rounded-xl border p-3.5" style={{ backgroundColor: C.bg, borderColor: `color-mix(in srgb, ${gold} 30%, transparent)` }}>
          <ol className="space-y-2">
            {orderPoints(talkingPoints).map((p, i) => {
              const structured = isStructured(p);
              const label = structured ? POINT_META[p.type].label : `${i + 1}.`;
              const labelColor = structured ? POINT_META[p.type].pillFg : gold;
              const text = typeof p === "string" ? p : p.text;
              return (
                <li key={i}>
                  <span className="text-[9px] font-bold uppercase tracking-wider mr-1.5" style={{ color: labelColor, letterSpacing: "0.06em" }}>{label}</span>
                  <span className="text-[11px] leading-snug" style={{ color: C.textPrimary }}>{text}</span>
                </li>
              );
            })}
          </ol>
        </div>
      )}
    </div>
  );
}
