"use client";

import { useEffect, useRef, useState } from "react";
import { Sparkles, RefreshCw, Target, Compass, Quote, ClipboardList, ChevronDown, UserRound, Lightbulb, ShieldAlert, Building2, Brain } from "lucide-react";
import { C } from "@/lib/design";
import LogoLoader from "@/components/LogoLoader";
import { useLocale } from "@/lib/i18n";

const gold = "var(--brand, #c9a83a)";

// Pre-Call Brief — three structured prompts (pain / fit / opener) generated by
// AI from the lead's enrichment + ICP.
//
// Two modes share one entry point:
//  1. PREMIUM (lead detail) — pass `leadId`. Full card with accent bars, icon
//     discs and a quoted opener. ALWAYS rendered, auto-generates on first view
//     when no brief is cached, with a Refresh button. (Fran 2026-06-05: the
//     brief must always be visible AND keep the pretty cards.)
//  2. COMPACT (the /queue pending-call rows) — pass only `talkingPoints`. A
//     collapsed toggle that expands inline, so it never overlaps neighbouring
//     rows. No auto-generation (we don't fire N AI calls when the queue opens).

type PointType = "snapshot" | "account" | "read" | "pain" | "fit" | "hook" | "opener" | "objection";
type TalkingPoint = { type: PointType; text: string };
type AnyPoint = TalkingPoint | string;

const ORDER: PointType[] = ["snapshot", "account", "read", "pain", "fit", "hook", "opener", "objection"];

function isStructured(p: AnyPoint): p is TalkingPoint {
  return typeof p === "object" && p !== null && "type" in p && "text" in p && p.type in POINT_META;
}

// Order structured points canonically (snapshot → … → objection); legacy
// strings / unknown types keep their original position at the end.
function orderPoints(points: AnyPoint[]): AnyPoint[] {
  const rank = (p: AnyPoint) => (isStructured(p) ? ORDER.indexOf(p.type) : 99);
  return points.map((p, i) => ({ p, i })).sort((a, b) => rank(a.p) - rank(b.p) || a.i - b.i).map((x) => x.p);
}

// i18n key for each point type label — used in BriefCard and CompactBrief
const POINT_LABEL_KEY: Record<PointType, string> = {
  snapshot: "brief.point.snapshot",
  account:  "brief.point.account",
  read:     "brief.point.read",
  pain:     "brief.point.pain",
  fit:      "brief.point.fit",
  hook:     "brief.point.hook",
  opener:   "brief.point.opener",
  objection:"brief.point.objection",
};

// Per-type icon only. The brief reads as one editorial piece, not eight
// colour-coded categories: every card shares a neutral surface + neutral
// label, and the icon (not a hue) carries the recognition. Emphasis is gold
// (brand / AI / structure) and lives in the header, the group labels and the
// Opener — never as a per-insight accent. These blocks are INSIGHTS, not
// system states, so red/orange/green (error/overdue/callback) are reserved
// and deliberately NOT used here. (Fran 2026-09-10: kill the rainbow.)
const POINT_META: Record<PointType, { icon: typeof Target }> = {
  snapshot:  { icon: UserRound },
  account:   { icon: Building2 },
  read:      { icon: Brain },
  pain:      { icon: Target },
  fit:       { icon: Compass },
  hook:      { icon: Lightbulb },
  opener:    { icon: Quote },
  objection: { icon: ShieldAlert },
};

// The brief reads as two groups: "the read" (who they are + how to play it) and
// "the play" (pain/fit/hook + what to say). Opener is rendered full-width at the
// end of the play group so the verbatim line stands out.
const READ_TYPES: PointType[] = ["snapshot", "account", "read"];
const PLAY_TYPES: PointType[] = ["pain", "fit", "hook", "objection"];

type Family = "read" | "play";
const familyOf = (t: PointType): Family => (READ_TYPES.includes(t) ? "read" : "play");

// V3 visual language (Fran-approved 2026-09-10) — THREE families, never a
// colour per insight. The read = cool slate, the play = warm gold-soft, the
// opener = gold. Recognition comes from a family-coloured card rail + a filled
// icon chip + a weighted label — not from eight hues. Container queries make
// the grids reflow on the brief's REAL width (full-width inside Lead Detail),
// independent of the viewport. All family hues are theme-aware CSS vars set
// below; everything else keys off the existing --c-* / --brand tokens.
const PCB_CSS = `
.pcb{container-type:inline-size;container-name:pcb;
  --pcb-read:#64748B;--pcb-read-label:#41506A;--pcb-play-label:#8A6B18;}
[data-theme="dark"] .pcb{--pcb-read:#7C8BA5;--pcb-read-label:#B4BFD2;--pcb-play-label:#E6C661;}
.pcb-read{--f:var(--pcb-read);--flabel:var(--pcb-read-label);
  --fcardbg:color-mix(in srgb,var(--pcb-read) 4%,var(--c-card));
  --fborder:color-mix(in srgb,var(--pcb-read) 26%,var(--c-border));}
.pcb-play{--f:var(--brand,#c9a83a);--flabel:var(--pcb-play-label);
  --fcardbg:color-mix(in srgb,var(--brand,#c9a83a) 5%,var(--c-card));
  --fborder:color-mix(in srgb,var(--brand,#c9a83a) 28%,var(--c-border));}
.pcb-card{position:relative;overflow:hidden;border-radius:12px;padding:13px 14px 13px 17px;height:100%;
  background:var(--fcardbg);border:1px solid var(--fborder);transition:box-shadow .15s,transform .12s;}
.pcb-card:hover{box-shadow:0 3px 12px rgba(0,0,0,.07);transform:translateY(-1px);}
.pcb-edge{position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--f);}
.pcb-chiprow{display:flex;align-items:center;gap:10px;margin-bottom:9px;}
.pcb-chip{width:28px;height:28px;border-radius:8px;flex:none;display:flex;align-items:center;justify-content:center;background:var(--f);}
.pcb-play .pcb-chip{background:color-mix(in srgb,var(--brand,#c9a83a) 86%,var(--c-card));}
.pcb-clabel{font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.1em;color:var(--flabel);}
.pcb-text{font-size:13.5px;line-height:1.55;color:var(--c-textBody);margin:0;}
.pcb-wash{border-radius:14px;padding:11px;}
.pcb-washR{background:color-mix(in srgb,var(--pcb-read) 9%,transparent);border:1px solid color-mix(in srgb,var(--pcb-read) 16%,var(--c-border));}
.pcb-washP{background:color-mix(in srgb,var(--brand,#c9a83a) 9%,transparent);border:1px solid color-mix(in srgb,var(--brand,#c9a83a) 17%,var(--c-border));}
.pcb-gread,.pcb-gplay{display:grid;gap:11px;grid-template-columns:1fr;align-items:stretch;}
@container pcb (min-width:560px){
  .pcb-gread{grid-template-columns:1fr 1fr;}
  .pcb-gread .pcb-span{grid-column:1 / -1;}
  .pcb-gplay{grid-template-columns:1fr 1fr;}
}
@container pcb (min-width:900px){
  .pcb-gread{grid-template-columns:1fr 1fr 1fr;}
  .pcb-gread .pcb-span{grid-column:auto;}
}
.pcb-opener{position:relative;overflow:hidden;border-radius:13px;margin-top:12px;
  background:color-mix(in srgb,var(--brand,#c9a83a) 9%,var(--c-card));
  border:1px solid color-mix(in srgb,var(--brand,#c9a83a) 34%,var(--c-border));}
.pcb-opener-edge{position:absolute;left:0;top:0;bottom:0;width:4px;
  background:linear-gradient(180deg,var(--brand,#c9a83a),color-mix(in srgb,var(--brand,#c9a83a) 72%,#000));}
.pcb-wm{position:absolute;top:-16px;right:16px;font-family:Georgia,serif;font-size:92px;line-height:1;
  color:color-mix(in srgb,var(--brand,#c9a83a) 7%,transparent);pointer-events:none;user-select:none;}
.pcb-oin{position:relative;padding:14px 18px 16px 21px;}
.pcb-ol{display:inline-flex;align-items:center;gap:8px;margin-bottom:8px;}
.pcb-ochip{width:22px;height:22px;border-radius:7px;flex:none;display:flex;align-items:center;justify-content:center;background:var(--brand,#c9a83a);}
.pcb-oltxt{font-size:10.5px;font-weight:800;text-transform:uppercase;letter-spacing:.11em;color:var(--pcb-play-label);}
.pcb-osay{font-size:9px;font-weight:700;letter-spacing:.04em;color:var(--c-textMuted);border:1px solid var(--c-border);border-radius:20px;padding:2px 7px;}
.pcb-oq{font-family:Georgia,'Times New Roman',serif;font-style:italic;font-size:16px;line-height:1.6;margin:0;}
`;

function GroupLabel({ children, family }: { children: string; family: Family }) {
  const color = family === "read" ? "var(--pcb-read-label)" : "var(--pcb-play-label)";
  const bar = family === "read" ? "var(--pcb-read)" : gold;
  return (
    <p className="flex items-center gap-2 text-[10px] font-extrabold uppercase mb-2.5" style={{ color, letterSpacing: "0.12em" }}>
      <span className="inline-block rounded-full" style={{ width: 16, height: 2, backgroundColor: bar }} />
      {children}
    </p>
  );
}

// Insight card (non-opener). Family-coloured rail + filled icon chip + weighted
// label give it presence and let it be scanned in 2-3s, all without a per-insight
// hue. `span` makes Snapshot full-width when the Read grid drops to two columns.
function BriefCard({ p, family, span }: { p: TalkingPoint; family: Family; span?: boolean }) {
  const { t } = useLocale();
  const Icon = POINT_META[p.type].icon;
  return (
    <div className={`pcb-card pcb-${family}${span ? " pcb-span" : ""}`}>
      <div className="pcb-edge" />
      <div className="pcb-chiprow">
        <div className="pcb-chip"><Icon size={16} strokeWidth={2.3} style={{ color: "#fff" }} /></div>
        <span className="pcb-clabel">{t(POINT_LABEL_KEY[p.type])}</span>
      </div>
      <p className="pcb-text">{p.text}</p>
    </div>
  );
}

// The Opener is the payoff — the verbatim line the seller reads aloud, so it's
// the highest-priority element: full-width, serif italic, a gold rail and a
// "say this" tag. A faint quotation watermark supports it without becoming
// decoration in its own right.
function OpenerCard({ p }: { p: TalkingPoint }) {
  const { t } = useLocale();
  return (
    <div className="pcb-opener">
      <div className="pcb-opener-edge" />
      <div className="pcb-wm" aria-hidden>&rdquo;</div>
      <div className="pcb-oin">
        <span className="pcb-ol">
          <span className="pcb-ochip"><Quote size={13} strokeWidth={2.4} style={{ color: "#fff" }} /></span>
          <span className="pcb-oltxt">{t(POINT_LABEL_KEY.opener)}</span>
          <span className="pcb-osay">{t("brief.opener.say")}</span>
        </span>
        <p className="pcb-oq" style={{ color: C.textPrimary }}>&ldquo;{p.text}&rdquo;</p>
      </div>
    </div>
  );
}

function LegacyCard({ text, n }: { text: string; n: number }) {
  return (
    <div className="flex gap-3 rounded-xl p-4 border" style={{ backgroundColor: C.surface, borderColor: C.border }}>
      <span className="flex items-center justify-center rounded-full shrink-0 text-[11px] font-bold"
        style={{ width: 24, height: 24, backgroundColor: gold, color: "#fff" }}>{n}</span>
      <p className="text-[13.5px] leading-snug" style={{ color: C.textPrimary }}>{text}</p>
    </div>
  );
}

export default function PreCallBrief({
  leadId,
  initialPoints,
  initialGeneratedAt,
  talkingPoints,
}: {
  leadId?: string;
  initialPoints?: AnyPoint[] | null;
  initialGeneratedAt?: string | null;
  /** Static prop (QueueClient): a pre-loaded list, no auto-generation. */
  talkingPoints?: AnyPoint[] | null;
}) {
  if (leadId) {
    return <PremiumBrief leadId={leadId} initialPoints={initialPoints ?? null} initialGeneratedAt={initialGeneratedAt ?? null} />;
  }
  return <CompactBrief talkingPoints={talkingPoints ?? null} />;
}

// ── Premium card (lead detail) ────────────────────────────────────────────────
function PremiumBrief({ leadId, initialPoints, initialGeneratedAt }: {
  leadId: string;
  initialPoints: AnyPoint[] | null;
  initialGeneratedAt: string | null;
}) {
  const { t, locale } = useLocale();
  const [points, setPoints] = useState<AnyPoint[] | null>(initialPoints);
  const [generatedAt, setGeneratedAt] = useState<string | null>(initialGeneratedAt);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const ranOnce = useRef(false);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/leads/${leadId}/talking-points`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ locale }),
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body?.error ?? `HTTP ${res.status}`);
      setPoints(body.points ?? null);
      setGeneratedAt(new Date().toISOString());
    } catch (e: any) {
      setError(e?.message ?? "Generation failed");
    } finally {
      setLoading(false);
    }
  }

  // Auto-fire once on first view when nothing is cached. Ref-guarded so it
  // never loops on re-render.
  useEffect(() => {
    if (ranOnce.current) return;
    if (points && points.length > 0) return;
    ranOnce.current = true;
    void generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const stamp = generatedAt
    ? new Date(generatedAt).toLocaleString("en-GB", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })
    : null;

  return (
    <div className="pcb relative rounded-2xl overflow-hidden mb-6 sheen-host"
      style={{
        background: `linear-gradient(180deg, color-mix(in srgb, ${gold} 4%, var(--card)) 0%, var(--card) 32%)`,
        border: "1px solid color-mix(in srgb, var(--brand, #c9a83a) 20%, var(--border))",
        boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
      }}>
      <style>{PCB_CSS}</style>
      {/* Header */}
      <div className="relative flex items-center justify-between px-6 pt-5 pb-4">
        <div className="flex items-center gap-3">
          <div className="rounded-xl flex items-center justify-center shrink-0 shadow-sm"
            style={{
              width: 42, height: 42,
              background: `linear-gradient(135deg, ${gold} 0%, color-mix(in srgb, ${gold} 65%, white) 100%)`,
              boxShadow: `0 4px 12px color-mix(in srgb, ${gold} 35%, transparent)`,
            }}>
            <Sparkles size={18} style={{ color: "#fff" }} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <p className="text-[15px] font-bold tracking-tight" style={{ color: C.textPrimary }}>
                Pre-Call Brief
              </p>
              <span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded-md"
                style={{
                  background: `linear-gradient(135deg, ${gold}, color-mix(in srgb, ${gold} 70%, white))`,
                  color: "#fff",
                  letterSpacing: "0.06em",
                }}>
                AI
              </span>
            </div>
            <p className="text-[11px] mt-0.5" style={{ color: C.textMuted }}>
              {loading ? (
                <span className="inline-flex items-center gap-1.5">
                  <Sparkles size={10} className="animate-pulse" /> {t("brief.loading")}
                </span>
              ) : stamp ? (
                <>{t("brief.generated").replace("{stamp}", stamp)}</>
              ) : (
                t("brief.hint")
              )}
            </p>
          </div>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className="inline-flex items-center gap-1.5 text-[11px] font-semibold px-3 py-1.5 rounded-lg transition-all hover:shadow-sm hover:-translate-y-px disabled:opacity-50 disabled:translate-y-0"
          style={{ backgroundColor: C.surface, color: C.textBody, border: `1px solid ${C.border}` }}
        >
          <RefreshCw size={11} className={loading ? "animate-spin" : ""} />
          {points && points.length > 0 ? t("brief.refresh") : t("brief.generate")}
        </button>
      </div>

      {/* Body */}
      <div className="relative px-6 pb-5">
        {error && (
          <p className="text-xs mb-3 px-3 py-2 rounded-md"
            style={{ color: "#991B1B", backgroundColor: "color-mix(in srgb, #DC2626 10%, transparent)", border: "1px solid color-mix(in srgb, #DC2626 28%, transparent)" }}>
            {error}
          </p>
        )}

        {points && points.length > 0 ? (() => {
          const ordered = orderPoints(points);
          const read = ordered.filter((p): p is TalkingPoint => isStructured(p) && READ_TYPES.includes(p.type));
          const play = ordered.filter((p): p is TalkingPoint => isStructured(p) && PLAY_TYPES.includes(p.type));
          const opener = ordered.find((p): p is TalkingPoint => isStructured(p) && p.type === "opener");
          const legacy = ordered.filter((p) => !isStructured(p)) as string[];
          // Older briefs persisted as plain strings / unknown types → simple list.
          if (read.length === 0 && play.length === 0 && !opener) {
            return <div className="grid gap-3">{legacy.map((t, i) => <LegacyCard key={i} text={String(t)} n={i + 1} />)}</div>;
          }
          return (
            <div className="space-y-4">
              {read.length > 0 && (
                <div>
                  <GroupLabel family="read">{t("brief.group.read")}</GroupLabel>
                  <div className="pcb-wash pcb-washR">
                    <div className="pcb-gread">
                      {read.map((p, i) => <BriefCard key={i} p={p} family="read" span={p.type === "snapshot"} />)}
                    </div>
                  </div>
                </div>
              )}
              {(play.length > 0 || opener) && (
                <div>
                  <GroupLabel family="play">{t("brief.group.play")}</GroupLabel>
                  {play.length > 0 && (
                    <div className="pcb-wash pcb-washP">
                      <div className="pcb-gplay">
                        {play.map((p, i) => <BriefCard key={i} p={p} family="play" />)}
                      </div>
                    </div>
                  )}
                  {opener && <OpenerCard p={opener} />}
                </div>
              )}
              {legacy.length > 0 && (
                <div className="grid gap-3">{legacy.map((t, i) => <LegacyCard key={i} text={String(t)} n={i + 1} />)}</div>
              )}
            </div>
          );
        })() : loading ? (
          <div className="rounded-xl overflow-hidden">
            <LogoLoader size={54} minHeight="200px" />
          </div>
        ) : (
          <div className="flex items-center justify-between gap-2 py-1">
            <p className="text-sm flex items-center gap-2" style={{ color: C.textMuted }}>
              <Sparkles size={13} /> {error ? t("brief.failed") : t("brief.building")}
            </p>
            <button
              type="button"
              onClick={generate}
              className="inline-flex items-center gap-1.5 text-[11px] font-semibold px-3 py-1.5 rounded-lg"
              style={{ color: gold, border: `1px solid color-mix(in srgb, ${gold} 35%, transparent)` }}
            >
              <RefreshCw size={11} /> {t("brief.generate")}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// ── Compact toggle (/queue rows) ──────────────────────────────────────────────
function CompactBrief({ talkingPoints }: { talkingPoints: AnyPoint[] | null }) {
  const { t } = useLocale();
  const [open, setOpen] = useState(false);
  if (!talkingPoints || talkingPoints.length === 0) return null;

  return (
    <div className="px-5 pb-3">
      <button
        onClick={() => setOpen(v => !v)}
        className="inline-flex items-center gap-1.5 text-[11px] font-semibold px-2.5 py-1.5 rounded-lg border transition-colors"
        style={{
          color: gold,
          borderColor: open ? `color-mix(in srgb, ${gold} 45%, transparent)` : C.border,
          backgroundColor: open ? `color-mix(in srgb, ${gold} 10%, transparent)` : C.card,
        }}
      >
        <ClipboardList size={12} /> {t("brief.toggle")}
        <ChevronDown size={11} style={{ transform: open ? "rotate(180deg)" : "none", transition: "transform 0.15s" }} />
      </button>

      {open && (
        <div className="mt-2 rounded-xl border p-3.5" style={{ backgroundColor: C.bg, borderColor: `color-mix(in srgb, ${gold} 30%, transparent)` }}>
          <ol className="space-y-2">
            {orderPoints(talkingPoints).map((p, i) => {
              const structured = isStructured(p);
              const label = structured ? t(POINT_LABEL_KEY[p.type]) : `${i + 1}.`;
              // Neutral labels for the insight rows; gold only for the legacy
              // numbered fallback (structure emphasis). No per-type colour.
              const labelColor = structured ? C.textMuted : gold;
              const text = typeof p === "string" ? p : p.text;
              return (
                <li key={i}>
                  <span className="text-[9px] font-bold uppercase tracking-wider mr-1.5" style={{ color: labelColor, letterSpacing: "0.06em" }}>{label}</span>
                  <span className="text-[11px] leading-snug" style={{ color: C.textPrimary }}>{text}</span>
                </li>
              );
            })}
          </ol>
        </div>
      )}
    </div>
  );
}
